// <auto-generated />
namespace jtf_Project.Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class kajshdjkasdh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kajshdjkasdh));
        
        string IMigrationMetadata.Id
        {
            get { return "201602030404568_kajshdjkasdh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
